#+TITLE: Home configuration files

* What is ~home~
:PROPERTIES:
:CUSTOM_ID: h:0272c5ac-0b7f-4ebb-91f0-defa66c2d285
:END:

This repository is using ~home-manager~ and ~nix~.

If you don't have ~nix~ installed, run ~curl https://nixos.org/nix/install | sh~ to install it.

- clone this repository in ~$HOME/.config/nixpkgs~
- create a `home.nix` file with the content you want.
  Some machines files already exists that you can use :

  #+begin_src nix
    { pkgs, ... }:

    {
      imports = [
        ./machines/hokkaido.nix
      ];
    }
  #+end_src

- run ~nix-shell https://github.com/rycee/home-manager/archive/master.tar.gz -A install~ (maybe twice :D)
- run ~echo -n "Passphrase: "; read -i PASSPHRASE; env PASSPHRASE=$PASSPHRASE home-manager switch;~

* Goal
:PROPERTIES:
:CUSTOM_ID: h:353cadbd-9a24-46af-8a87-72e3b3b822d6
:END:

The goal of is repository is to be able to have a way to setup dotfiles and packages in
/one go/, sharing those configuration between multiple computers. The documentation part
is using (or /will/) =org-mode= following principles of "literate programming": a
combination of ordinary language and inline code blocks.

This means it could become the /monorepo/ of my configuration, slowly migrating other
repositories into this one (like [[https://github.com/vdemeester/emacs-config][~emacs-config~]]). This repository should be the source of
truth of all my configuration.

This will be a all-time work-in-progress, so please beware that things might change
dramatically or even not working anymore 😛.

** TODO Organization of =org-mode=
:PROPERTIES:
:CUSTOM_ID: h:b74304bf-e7e6-4425-9123-e50eca3eb8fa
:END:

As I'm slowly, but _surely_, going to have =org-mode= files for literate configuration
files in this repository, I have to think of how to organize files in order to end up with
one huge file.

** TODO Nix files and =ansible=
:PROPERTIES:
:CUSTOM_ID: h:daf2fc12-0c9f-4008-9aa1-f0c22bdb616d
:END:

This repository holds [[https://nixos.org/nix/][nix]] files and [[https://www.ansible.com/][ansible]] configurations too. Those two are targeting
different machines, although, the nix files are used in almost all my machines (whereas
ansible configuration is just used on non-NixOS setups).

* COPYING
:PROPERTIES:
:CUSTOM_ID: h:716e598e-3b1a-4e48-a72b-608c3a970db9
:END:

Copyright (c) 2018-2020 Vincent Demeester <vincent@sbr.pm>

This file is free software: you can redistribute it and/or modify it
under the terms of the GNU General Public License as published by the
Free Software Foundation, either version 3 of the License, or (at
your option) any later version.

This file is distributed in the hope that it will be useful, but
WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
General Public License for more details.

You should have received a copy of the GNU General Public License
along with this file.  If not, see <http://www.gnu.org/licenses/>.
