# This file was generated by https://github.com/kamilchm/go2nix v1.2.1
[
  {
    goPackagePath = "github.com/containous/flaeg";
    fetch = {
      type = "git";
      url = "https://github.com/containous/flaeg";
      rev = "23af69148a91eb9fd61bd84baa2b011a03a445bd";
      sha256 = "01bwl8yb5bsn14vlp92xbw5hfn8lsis745rgzbya6l3ca8sbv8nl";
    };
  }
  {
    goPackagePath = "github.com/google/go-github";
    fetch = {
      type = "git";
      url = "https://github.com/google/go-github";
      rev = "2ae5df7848328c214a48cec94c7d410cf8526527";
      sha256 = "115pynpgxbg3khpg8n9zwwlb0krr7ac56r1if9hp5kqnci3r5w6g";
    };
  }
  {
    goPackagePath = "github.com/google/go-querystring";
    fetch = {
      type = "git";
      url = "https://github.com/google/go-querystring";
      rev = "53e6ce116135b80d037921a7fdd5138cf32d7a8a";
      sha256 = "0lkbm067nhmxk66pyjx59d77dbjjzwyi43gdvzyx2f8m1942rq7f";
    };
  }
  {
    goPackagePath = "github.com/ldez/go-git-cmd-wrapper";
    fetch = {
      type = "git";
      url = "https://github.com/ldez/go-git-cmd-wrapper";
      rev = "e27263e23bd292ec54bd9519f0e727395a949a91";
      sha256 = "01gz12360yfp6wylsjw522svj2vdh567yrdy3xghgh6hp20bxvb9";
    };
  }
  {
    goPackagePath = "github.com/mattn/go-colorable";
    fetch = {
      type = "git";
      url = "https://github.com/mattn/go-colorable";
      rev = "efa589957cd060542a26d2dd7832fd6a6c6c3ade";
      sha256 = "0kshi4hvm0ayrsxqxy0599iv81kryhd2fn9lwjyczpj593cq069r";
    };
  }
  {
    goPackagePath = "github.com/mattn/go-isatty";
    fetch = {
      type = "git";
      url = "https://github.com/mattn/go-isatty";
      rev = "6ca4dbf54d38eea1a992b3c722a76a5d1c4cb25c";
      sha256 = "0zs92j2cqaw9j8qx1sdxpv3ap0rgbs0vrvi72m40mg8aa36gd39w";
    };
  }
  {
    goPackagePath = "github.com/mgutz/ansi";
    fetch = {
      type = "git";
      url = "https://github.com/mgutz/ansi";
      rev = "9520e82c474b0a04dd04f8a40959027271bab992";
      sha256 = "00bz22314j26736w1f0q4jy9d9dfaml17vn890n5zqy3cmvmww1j";
    };
  }
  {
    goPackagePath = "github.com/ogier/pflag";
    fetch = {
      type = "git";
      url = "https://github.com/ogier/pflag";
      rev = "45c278ab3607870051a2ea9040bb85fcb8557481";
      sha256 = "0620v75wppfd84d95n312wpngcb73cph4q3ivs1h0waljfnsrd5l";
    };
  }
  {
    goPackagePath = "github.com/pkg/errors";
    fetch = {
      type = "git";
      url = "https://github.com/pkg/errors";
      rev = "816c9085562cd7ee03e7f8188a1cfd942858cded";
      sha256 = "1ws5crb7c70wdicavl6qr4g03nn6m92zd6wwp9n2ygz5c8rmxh8k";
    };
  }
  {
    goPackagePath = "golang.org/x/net";
    fetch = {
      type = "git";
      url = "https://go.googlesource.com/net";
      rev = "1e491301e022f8f977054da4c2d852decd59571f";
      sha256 = "1wc18flnz99bip2j1gpnvr3qdp1y7wgyvawlvvc8rmd6ggf5f2yq";
    };
  }
  {
    goPackagePath = "golang.org/x/oauth2";
    fetch = {
      type = "git";
      url = "https://go.googlesource.com/oauth2";
      rev = "ec22f46f877b4505e0117eeaab541714644fdd28";
      sha256 = "130mzy6mn1kik21zswv2kddfc0n53p4xvb2f64v7diykdkmb7gs5";
    };
  }
  {
    goPackagePath = "gopkg.in/AlecAivazis/survey.v1";
    fetch = {
      type = "git";
      url = "https://gopkg.in/AlecAivazis/survey.v1";
      rev = "e752db451e07e09c7d7dc8cada807a44bdb0fd47";
      sha256 = "00fhmsaymrf86pg246cqxvfrivgfkyg3i0aixsp3sn15hg3i0vlq";
    };
  }
]
