AUDIO_ENABLE = no
# CAPS_WORD_ENABLE = yes
# AUTO_SHIFT_ENABLE = yes
COMBO_ENABLE = yes
COMMAND_ENABLE = no
CONSOLE_ENABLE = no
KEY_OVERRIDE_ENABLE = yes
LEADER_ENABLE = yes
REPEAT_KEY_ENABLE = yes
SPACE_CADET_ENABLE = no
TAP_DANCE_ENABLE = yes
LAYER_LOCK_ENABLE = yes

EXTRAFLAGS += -flto
