#+TITLE: Podcasts
#+date: <2013-10-12 Sat>
#+filetags: music podcast
#+setupfile: ../templates/post.org

* Introduction

#+BEGIN_QUOTE
  Voici un petit billet présentant les différents podcast que j'écoute
  plus ou moins régulièrement.
#+END_QUOTE

J'écoute énormément de musique et de podcast ; je passe beaucoup de
temps avec des écouteurs sur la tête ou la chaine hifi en route. Les
podcasts ont une grande place. Voici une liste plus ou moins bien triés
de ceux auxquels je suis souscrit et/ou que j'écoute en ce moment. Je
tiendrais peut-être ce post à jour ou en créerait un nouveau sinon :-).

* Geek & co
   :PROPERTIES:
   :CUSTOM_ID: geek-co
   :END:

Je suis un developpeur, un geek et convaincu des logiciels libres, les
podcasts qui suivent reflète assez cette partie là de mon identité.

- [[http://www.captainweb.net/][L'apéro de Captain (fr)]] : dans le
  genre geeky, déjanté et sauvage, en français, on ne fait pas mieux.
  Pas vraiment safe for work, et pas tout à fait "libriste" comme
  j'aime, les tranches de rires sont garanties ; même si parfois on est
  un peu verreux d'avoir écouter jusqu'à la fin et le bien nommé
  "wazzuf".
- [[http://www.agencetousgeeks.com/][Agence Tous Geeks (fr)]] : fils
  caché de l'apéro du captain, on y retrouve des amis (et membres de ce
  dernier), mais c'est un peu plus calme.
- [[http://bazingcast.com/about/][Bazingcast (fr)]] : podcast geek, plus
  posé que les deux précédents mais avec des débats, des trolls et tout
  ce que l'on peut attendre de geeks.
- [[http://www.captainposix.net/][Parole de Tux (fr-be)]] : podcast
  venant de nos voisin belge, pas trop long et plutôt sympa ; et si
  comme moi vous adorez l'accent belge, c'est le top.
- [[http://faif.us/][Free as in Freedom (en)]] : podcast parlant de
  logiciel libre principalement côté license, truc légal, etc.. en
  anglais, faut parfois s'accrocher.
- [[http://episodes.gitminutes.com/][Git Minutes (en)]] : podcast à
  propos de Git et des outils de son écosystème (vcsh, etc..).

* Radio
   :PROPERTIES:
   :CUSTOM_ID: radio
   :END:

J'aime bien la radio, bien plus que la télévision (que j'allume si peu
qu'à chaque fois la box se met à jour =;-p=).

- [[http://www.franceinter.fr/emission-laura-leishman-project][France
  Inter - LLP (Laura leishman Project)]]
- [[http://radiofrance-podcast.net/podcast09/rss_12265.xml][Le Mouv' -
  Laura Leishman Project]]
- [[http://www.franceinter.fr/emission-interception][France Inter -
  Interception]]
- [[http://www.la-bas.org/][France Inter - là-bas si j'y suis]]
- [[http://www.franceculture.fr/podcast/4689840][France Culture -
  Pixel]]
- [[http://www.franceculture.fr/podcast/4685228][France Culture - Place
  de la toile]]
- [[http://www.franceculture.fr/podcast/4689418][France Culture -
  Philippe Meyer]]
- [[http://radiofrance-podcast.net/podcast09/rss_12582.xml][Le Mouv' -
  Glitch (sur le Mouv')]]
- [[http://radiofrance-podcast.net/podcast09/rss_12691.xml][Le Mouv' -
  Code Source]]
- [[http://radiofrance-podcast.net/podcast09/rss_12190.xml][Le Mouv' -
  Suivez le geek]]
- [[http://www.divergence-fm.org/-http-www-divergence-fm-org-ecrire-exec-rubrique-id_rubrique-61-.html][Divergence
  Numerique]]

* Musique
   :PROPERTIES:
   :CUSTOM_ID: musique
   :END:

Les podcast suivant sont purement musique, tous musique techno ou trance
(que j'aime bien).

- [[http://podcasts.flaix.fr/corstencountdown][Ferry Corsten - Corsten
  Countdown]]
- [[http://www.galexmusic.com/podcast/gareth.xml][Gareth Emery Podcast]]
- [[http://feedproxy.feedburner.com/Tiestos_club_life][Tiesto Club
  Life]]
- [[http://oakenfold.libsyn.com/rss][Oakenfold Perfecto Podcast]]
