#+title: Redesign et Résolutions
#+date: <2014-03-24 Mon>
#+filetags: jekyll design images redesign
#+setupfile: ../templates/post.org

* Introduction

Un /tout petit/ post pour parler rapidement, entre autre, du redesign de
[[http://vincent.demeester.fr][vincent.demeester.fr]] et de mes
résolutions.

* Redesign
   :PROPERTIES:
   :CUSTOM_ID: redesign
   :END:

Les raisons de ce redesign sont assez simple : je change d'employeur et
de ville (retour sur Paris =\o/=). Cela fait pas mal de changement, et
en voulant mettre à jour la page d'accueil (ce que je n'ai toujours pas
fait =;-P=), j'avais envie de /déménager/ le site en quelques sortes.

Pour l'inspiration c'est assez facile à trouver, regarder
[[http://medium.com][medium]], le site de
[[http://www.viksit.com/][Viksit Gaur]] ou encore celui de
[[http://silent-strength.com/][Michael]] (coucou =:-P=). J'adore ce
genre de site, assez épuré mais avec une partie fixe (à gauche ou à
droite) et avec des images changeantes.

Les images en fond de l'espace de gauche peuvent changer d'une page à
l'autre. Je suis en train de m'amuser un peu avec
[[http://jekyllrb.com][Jekyll]]. Il faut que je trouve un moyen
d'optimiser un peu les images que j'utilise parce que là je joue un peu
le bourrin.

* Résolutions
   :PROPERTIES:
   :CUSTOM_ID: résolutions
   :END:

Nouvelle année, nouveau boulot, implique nouvelles résolutions. Il y a
deux aspects à ces /résolutions/ : sur un plan
informatique/geek/travail/organisation, et sur un plan purement
/physique/.

Mon retour sur Paris devrait me permettre de participer à un peu plus
d'évènements, notamment du côté des Java User Group, mais aussi FSFE, et
j'en passe. Je compte également continué à jouer le /factotum/ en me
gardant un peu de temps au niveau personnel pour travailler sur des
aspects /geek/ que je n'aurais peut-être pas l'occasion de pratiquer au
travail. Au niveau de mes /points d'entrées/ sur le web, je compte
remettre un peu en route la partie blog de ce site et tourner
shortbrain.org (ou autre) en un site plus "documentation" en me basant
sur mes notes (powered by [[http://org-mode.org][org-mode]]). Je me suis
également remis à [[https://www.gnu.org/software/emacs/][Gnu Emacs]] et
/oh god/ qu'est-ce que c'est bon =:-D=.

Au niveau phyisque, dans la continuité de la fin 2012, l'année 2013 a
probablement été la pire de ma vie. Les problèmes de dos c'est pas
facile tous les jours.. En février, j'avais peur de ne jamais remonter
sur un vélo ; en Mai je remontais pour la première fois sur le vélo, en
Septembre je faisais 40km par semaine et en décembre j'étais presque
capable de faire 30km en une journée. Mème si l'année 2014 a mal
commencé (je me suis felé un côte en Janvier), mes objectifs pour cette
année et les futurs sont nettement plus positif. Le
[[http://fitbit.com][fitbit]] que j'ai acquis en Février me permet
d'avoir un objectif de marche (certes assez modeste) de 10000 pas et
8,05 km par jour. Je compte bien me fixer d'autre objectifs : monter la
barre plus haut (15000 voir plus), faire 50km de vélo sur une journée.

Les objectifs physiques à très long termes sont également assez simples
: retrouver ma forme physique et ne plus être géné à cause du dos. En
gros c'est : être capable de faire 120km de vélo et monter des cols (Col
du Sapenay, Mont Revard) et à long terme, faire des courses de footing
(i.e. 10km, Paris-Versaille, Semi-marathon, marathon :D).

Sur ce, je vais retourner à mes cartons :-P.
