#+title: Random thoughts after 2 years
#+date: <2022-05-05 Thu>
#+filetags: #home
#+setupfile: ../templates/2022.post.org

* Introduction

It has been a while since I wrote something here, and I think the reason for that is…
writing is not really central to my day-to-day "flow". For example, I do write /a lot/ as
I do journaling. But writing a blog post or an article is longer, and usually, it is
happening in my =org= folders.

I am currently trying to re-organize a bit the website and my publishing workflow to
reduce as much as possible the "noise" between when and what I write and when and where it
is published. I think I've been inspired by [[https://joelhooks.com/digital-garden][Joel's digital garden]] article.

#+begin_quote
For as long as I've been writing words on the internet, I've connected the words that I create in a paginated chronological format. This is the "traditional" blog style website. A linear newest-first sorted chronologically oriented list of posts.

I'm convinced that paginated posted sorted chronologically fuckin' sucks.

What makes a garden is interesting. It's personal. Things are organized and orderly, but with a touch of chaos around the edges.

Just like plants in the garden I've got posts that are in various stages of growth and nurturing. Some might wither and die, and others (like this one you are reading) will flourish and provide a source of continued for the gardener and folks in community that visit 👋

Chronologically sorted pages of posts aren't how people actually use the internet.
#+end_quote

I am also going to re-design a little bit (as little as possible really) to be even more
aligned with my current "thoughts". And there, I am taking inspiration from [[https://www.la-grange.net/][La Grange]] from
[[https://www.la-grange.net/karl/][Karl Dubost]]. Karl keeps the "design" (or style or whatever) of its page as they are / were
when he is published the content. This means, a page written 10 years ago, will be
rendered the same (/with devil in details if the browser changed something or course/), 10
years ago or now. And, /for some reason/, this is *really* appealing to me.

#+begin_src emacs-lisp
(defun read-file (filePath)
  "Return FILEPATH's file content."
  (with-temp-buffer
    (insert-file-contents filePath)
    (buffer-string)))
#+end_src

#+begin_quote
HTML export of drawer with NAME and CONTENT.
name is the name of the drawer, that will be used as class.
content is the content of the drawer

— Vincent Demeester
#+end_quote
