[networks.vpn]
v4 = "10.100.0.0" #/24

[hosts.naruhodo]
network = "vpn"
ssh = { pubkey = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIO7zGAceSiqFtWHwt7HVjN24SCyWCC26l6YrgUP/qtPc vincent@naruhodo" }

[hosts.naruhodo.wireguard]
pubkey = "XXyyJ9GlIiZnUm+Bkpz+NSrFiosjfY4FB2PgLXVPLkI="
addrs = { v4 = "10.100.0.15" }

[hosts.wakasu]
network = "vpn"
ssh = { pubkey = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIITpgxTnebhBnFyjWiF1nPM7Wl7qF+ce3xy/FvA4ZVN+ vincent@wakasu" }
addrs = { v4 = "192.168.1.77" }

[hosts.wakasu.wireguard]
pubkey = "qyxGnd/YJefqb4eEPqKO5XinvNx14fPcuZMNeYuBvSQ="
addrs = { v4 = "10.100.0.8" }

[hosts.aomi]
network = "vpn"
ssh = { pubkey = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIHJ3QqVCUiE4BIFKTJLN6mSnp9bLSnJ3gE8ScbAajGsH vincent@aomi", gpgRemoteForward = true }
addrs = { v4 = "192.168.1.23" }

[hosts.aomi.wireguard]
pubkey = "XT4D9YLeVHwMb9R4mhBLSWHYF8iBO"
addrs = { v4 = "10.100.0.17" }

[hosts.shikoku]
network = "vpn"
ssh = { pubkey = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIGxstR3xEf87leVVDS3GVPx8Ap9+eP+OfkSvM26V54XP vincent@shikoku", gpgRemoteForward = true }
addrs = { v4 = "192.168.1.24" }

[hosts.shikoku.builder]
maxJobs = 8
systems = [ "x86_64-linux", "aarch64-linux", "armv7l-linux", "armv6l-linux" ]
features = [ "big-parallel", "kvm", "nixos-test" ]

[hosts.shikoku.wireguard]
pubkey = "foUoAvJXGyFV4pfEE6ISwivAgXpmYmHwpGq6X+HN+yA="
addrs = { v4 = "10.100.0.2" }

[hosts.sakhalin]
network = "vpn"
ssh = { pubkey = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIHspuKkxiLuuRjNsLCXFA51DGWdHo/9TGW4YZmQGKbm+ vincent@sakhalin", gpgRemoteForward = true }
addrs = { v4 = "192.168.1.70" }

[hosts.sakhalin.wireguard]
pubkey = "OAjw1l0z56F8kj++tqoasNHEMIWBEwis6iaWNAh1jlk="
addrs = { v4 = "10.100.0.16" }

[hosts.kerkouane]
network = "vpn"
# addrs = { v4 = "167.99.17.238" } # FIXME probably not right
ssh = { pubkey = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAILtEnw+3WMa9ESRyKdBUp/OHd8NPQdHLoqQ58L3YXF1o vincent@kerkouane", gpgRemoteForward = true, command = "tmux new -A -s default" }

[hosts.kerkouane.wireguard]
addrs = { v4 = "10.100.0.1" }
port = 51820

[hosts.aion]
network = "vpn"
addrs = { v4 = "192.168.1.49" }

[hosts.aion.wireguard]
pubkey = "T8qfsBiOcZNxUeRHFg+2FPdGj4AuGloJ4b+0uI2jM2w="
addrs = { v4 = "10.100.0.49" }

[hosts.athena]
network = "vpn"
addrs = { v4 = "192.168.1.183" }

[hosts.athena.wireguard]
pubkey = "RWqH7RdIXg+YE9U1nlsNiOC7jH8eWjWQmikqBVDGSXU="
addrs = { v4 = "10.100.0.83" }

[hosts.demeter]
network = "vpn"
addrs = { v4 = "192.168.1.182" }

[hosts.demeter.wireguard]
pubkey = "/bBh4gvDty/AA2qIiHc7K0OHoOXWmj2SFFXdDq8nsUU="
addrs = { v4 = "10.100.0.82" }

[hosts.honshu]
network = "vpn"

[hosts.honshu.vpn]
addrs = { v4 = "10.100.0.17" }
pubkey = "vzkizZZMoM8yi5bjKiDZN1vYydZY6NKJhv9OqwSTFAk="

[hosts.k8sn1]
addrs = { v4 = "192.168.1.130" }

[hosts.k8sn2]
addrs = { v4 = "192.168.1.131" }

[hosts.k8sn3]
addrs = { v4 = "192.168.1.132" }

[ssh.keys]
vincent = [ "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICl4uBPx98p0m1ra4nKxaDvCP8TCou5J10gFUpYAuzp9 u0_a103@localhost", "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAINsbGtpU/w7Ff3O7hJ1QoO/5CuCrssBXrT+iHev/+rbf Generated By Termius" ]
houbeb = [ "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIGUnBCTxRoIDhExcSaiirM5nf2PIcTMDUodYlGNvqfmD Generated By Termius" ]
root = [ "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCDr3bRw6r43BVOltmTXtDQAtZlJ/viBrCb58fG8suSdO97xLEGukZzf1QX46aXQEsenfKOalcd+OrukcoVIiZtlh1BHAaBB09Q0vKjtB1zKcUdZQYb6kA21/ItpW3gNsZq5M98QpwS9soJOLSccQosDoVBWDcHx72Kpzp2x4seKyAIpb1gtPnQjnnwA7urTcANw7CU8lmB3UtJZNPHclJNKso7h0ZBapausk9t0xGP18rmzQAe2ipa6pwUzS5rRq+j0LiY/JZQaQWBfc1i3IcKictKW5EykKmywJcwmr/PcTdcgTT4FaD+b1t1QAPLV82HxGzOYQO+/WBptBdq7Ss5 openpgp:0x86ADD81F", "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDJoArpBsTXr3m6q2QnA1vI1DSwmgdU0OAp7DUxcxl9CJfeZIEs/iAerk8jmHgJ2xCEF6SpzI0FWSQIXy8dKpF4wLJ0tCoq5LqQx3jEzy3NUBLfxK+/Baa1te4qG2YImlgnzmEEm5uZlCGZRY2L/U9+4Hwo1AgD69Zzin6QGh2pyTWpmZ/WyhwIfGgqsnlM9XlaVzlMHYfStDi+rUU6XEAfdSqo1SnWKDBHc3mDYGTVhfAlt2LucLKu7oI2MsSlSxva072BExctadtB3TGHbt8gRJZj8CdwgRNhT+hFfbsL6YDvQn6dhTSMuiD8sBEvVble0Nj4p+Q6ROCRIuMuhgh3 cardno:000610153832", "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIGxstR3xEf87leVVDS3GVPx8Ap9+eP+OfkSvM26V54XP vincent@shikoku" ]
