#+title: A Digital Garden you say…
#+subtitle: Let's try to describe what this "website" is about ✍️.
#+date: <2022-06-24 Fri>
#+filetags: #home
#+SETUPFILE: ../../templates/2022.org

As I said in [[file:random.org]["Random thoughts after 2 years"]], I've been inspired by [[https://joelhooks.com/digital-garden][Joel's digital garden]]
article. This article aims to provide a bit of how I intend to maintain this space from
now on.

This space is inspired by [[https://www.la-grange.net/][a]] [[https://larlet.fr/david/][lot]] [[https://joelhooks.com/][of]] other spaces, but adapted to my vision. I think I've
always struggled with the blog approach. I sometimes want to publish things that are not
related to time. That can be true no matter when you read it. The opposite is true as
well.

I really like the way Joel speaks about it.

#+begin_quote
While not everybody has or works in a dirt garden, we all share a
familiarity with the idea of what a garden is.

A garden is usually a place where things grow.

Gardens can be very personal and full of whimsy or a garden can be a
source of food and substance.

We gather and work together in community gardens to share the labor as
well as the rewards of a collective effort.

It's a comparison that you can take very far. From "planting seeds"
and "pulling weeds" to tending mutiple gardens that each serve an
individual need or desired outcome.

Like with real gardens, our digital gardens are a constant ebb and
flow towards entropy.

Weeds take over. Left untended the Earth will reclaim what belongs to
it.

The same is true for our digital gardens here on the internet.
#+end_quote

There is quite some things I still did not figure out:
- I am not sure how to handle =rss= yet. It is slightly easier for a time-based approach
  such as a "blog".
