#+TITLE: vincent.demeester.fr

This is my website source code and content. Here lives /or should live/ all that matters and
is required to run and publish my website, anywhere.

- It is statically published and can be build and browsed locally
- It is as simple, and reproductible as possible
  + as little dependency as possible, most likely only =emacs= (if that's not too much already).
  + using ~nix~ to make sure it is reproductible
- It is /temporal/, meaning if I change the style, theme, … the previous pages are still
  using the one at their time.

* Structure

This repository holds the source of the website. The actual generated website is build, in
a reproducible manner, package and deployed. It can also be served locally, with tools
like =miniserve= or even without.

- =content= holds the content, so =org= files or =html= files, …
- =public= holds the generated content.

* Links

- [[https://github.com/NixOS/nixos-homepage/blob/master/flake.nix][nixos homepage flake]]
- [[https://git.sr.ht/~aasg/haunted-blog][aasg's most experimental weblog – haunted edition]] — using flake
  + [[https://sr.ht/~aasg/snowweb/][SnowWeb – a webserver for Nix flakes]]
